ci:
  autofix_prs: false
  autoupdate_schedule: quarterly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: no-commit-to-branch
  - id: debug-statements
  - id: check-merge-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-toml

- repo: https://github.com/neutrinoceros/inifix.git
  rev: v4.4.3
  hooks:
  - id: inifix-format

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.3.0
  hooks:
  - id: black

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.5
  hooks:
  - id: ruff
    args: [--fix, --show-fixes]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
