name: CI (bleeding-edge)
# weekly check for stability against dev version of
# - numpy
# - matplotlib,
# - scipy

on:
  push:
    branches:
    - main

  pull_request:
    paths:
    - .github/workflows/bleeding-edge.yml

  schedule:
    # run this once a week (wednesday) at 3 am UTC
  - cron: 0 3 * * 3

  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    name: Test nightly dependencies

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13-dev
    - uses: astral-sh/setup-uv@v2
      with:
        enable-cache: true
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        uv venv
        uv pip install numpy matplotlib scipy --pre --no-build --extra-index-url \
          https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
        uv pip install .
        uv pip install --requirement requirements/tests_all.txt

    - run: uv pip list

    - name: Run pytest
      run: |
        source .venv/bin/activate
        pytest --color=yes -ra
