name: CI (bleeding-edge)
# weekly check for stability against dev version of
# - numpy
# - matplotlib,
# - scipy

on:
  push:
    branches:
    - main

  pull_request:
    paths:
    - .github/workflows/bleeding-edge.yml

  schedule:
    # run this once a week (wednesday) at 3 am UTC
  - cron: 0 3 * * 3

  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    name: Test nightly dependencies

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Setup Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: 3.13-dev
    - uses: astral-sh/setup-uv@887a942a15af3a7626099df99e897a18d9e5ab3a # v5.1.0
    - name: Configure uv
      run: |
        echo "UV_PYTHON_PREFERENCE=only-system" >> $GITHUB_ENV
        pin=${{ matrix.python-version }}
        echo "UV_PYTHON=${pin%-dev}" >> $GITHUB_ENV
        echo "UV_PRERELEASE=allow" >> $GITHUB_ENV
        echo "UV_INDEX=https://pypi.anaconda.org/scientific-python-nightly-wheels/simple" >> $GITHUB_ENV
        echo "UV_INDEX_STRATEGY=unsafe-best-match" >> $GITHUB_ENV

    - name: Run pytest
      run: |
        uv run --no-editable --all-extras --group test \
          pytest --color=yes
