name: CD
on:
  push:
    tags: v*
  pull_request:
    paths:
    - .github/workflows/cd.yml

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/nonos
    permissions:
      id-token: write
    steps:
    - name: Checkout Source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Setup Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
      with:
        python-version: 3.x
    - name: Install build dependencies
      run: python -m pip install build wheel
    - name: Build distributions
      shell: bash -l {0}
      run: python -m build
    - name: Publish package distributions to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
