name: CI
on: [push, pull_request]
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10']
        dependencies: [dev]
        include:
          - os: ubuntu-18.04
            python-version: '3.8'
            dependencies: 'dev,minimal'

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup package (UNIX)
      if: runner.os != 'Windows'
      run: python -m pip install .["$dependencies"]
      env:
        dependencies: ${{ matrix.dependencies }}

    - name: Setup package (Windows)
      if: runner.os == 'Windows'
      run: python -m pip install .["$env:dependencies"]
      env:
        dependencies: ${{ matrix.dependencies }}


    - name: Run test
      run: |
        pytest -vvv
