name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - README.md

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10']
        dependencies: [dev]
        include:
          - os: ubuntu-20.04
            python-version: '3.8'
            dependencies: 'dev,minimal'

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build (UNIX)
      if: runner.os != 'Windows'
      run: python -m pip install .["$dependencies"]
      env:
        dependencies: ${{ matrix.dependencies }}

    - name: Build (Windows)
      if: runner.os == 'Windows'
      run: python -m pip install .["$env:dependencies"]
      env:
        dependencies: ${{ matrix.dependencies }}


    - name: Run pytest
      run: pytest --color=yes


  type-check:
    runs-on: ubuntu-latest
    name: type-checking

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Build
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install .[typecheck]

    - name: Run mypy
      run: mypy nonos
